"""Main module
https://github.com/pthom/mini_bundle
"""


# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:mini_bundle.h>    ####################
# empty!
####################    </generated_from:mini_bundle.h>    ####################

# </litgen_stub> // Autogenerated code end!
